Repository polyse/database, pull requests merged in 2020-05, with the labels that each got.

#1 SE-6 Feature frame
  .gitignore
  Makefile
  README.md
  cmd/database/config.go
  cmd/database/main.go
  cmd/database/wire.go
  cmd/database/wire_gen.go
  go.mod
  go.sum
  internal/web/web.go
Labels: enhancement

#2 SE-8 filters
  go.mod
  go.sum
  pkg/filters/filters.go
Labels: enhancement

#3 SE-11 first db commit
  .gitignore
  README.md
  cmd/database/config.go
  cmd/database/init.go
  cmd/database/main.go
  cmd/database/wire.go
  cmd/database/wire_gen.go
  go.mod
  go.sum
  internal/collection/manager.go
  internal/collection/manager_test.go
  internal/collection/proc.go
  internal/collection/proc_test.go
  pkg/filters/filters.go
Labels: enhancement

#5 SE-12 db find
  Makefile
  cmd/database/init.go
  cmd/database/main.go
  go.mod
  go.sum
  internal/api/api.go
  internal/collection/manager_test.go
  internal/collection/proc.go
  internal/collection/proc_test.go
Labels: documentation, enhancement

#7 Fix not found err
  internal/api/api.go
  internal/collection/proc.go
Labels: bug

#10 Fix golint
  README.md
  cmd/database/main.go
  cmd/database/wire.go
  go.mod
  go.sum
  internal/api/api.go
  internal/collection/manager.go
  internal/collection/proc.go
  internal/collection/proc_test.go
Labels: enhancement

#11 Bugfix empty request
  internal/api/api.go
Labels: bug
